name: 🚀 Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: 🚀 Release
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Repo
        uses: actions/checkout@v4

      - name: 🥡 Install PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: 🟢 Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: 🧩 Install Dependencies
        run: pnpm install

      - name: 📣 Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          title: 'chore(release): version packages 🦋'
          publish: pnpm release
          version: pnpm version-packages
          commit: 'chore(release): version packages 🦋 [skip ci]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
